# -*- coding: utf-8 -*-
"""FST_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18lBcw9JWvmimavfuZuiQnQounFOE-3wB

**Multiple condition**
"""

#Write a program to make a calculator
a=int(input("Enter the no 1: "))
b=int(input("Enter the no 2: "))
print("1.Addition 2.Subtraction 3.Multiplication 4.Dividision")
ch=int(input("Enter your choice: "))
if(ch==1):
  print(a+b)
elif(ch==2):
  print(a-b)
elif(ch==3):
  print(a*b)
elif(ch==4 and b!=0):
  #here we may get zero division error if second input is 0
  if(b==0):
    print("can't divide by zero")
  else:
    print(a/b)
else:
  print(".....invalid choice.....")

#JIVANSATHI.COM

#Accept the information about jivansathies
age=int(input("Enter the age: "))
gender=input("Enter the gender of the person(M/F): ")
#using nested condition statements
if(gender=="F"):
  print("You will find your fioncee")
  if(age>=18):
    print("You are eligible to get married...proceed to find your partner")
  else:
    print("You are under aged to get married....Please wait for ",18-age," years")

#using mujltiple condition statements
elif(gender=="M" and age>=21):
  print("You are eligible to find your partner..")

elif(gender=="M" and age<21):
  print("You are not eligible to find your partner..")

#jivansathi.com
if(gender=="F" and age>=21 or gender=="M" and age>=18):
  print("eligible")

else:
  print("not eligible")

#find maximum and minimum
a=int(input("Enter the age 1: "))
b=int(input("Enter the age 2: "))
c=int(input("Enter the age 3: "))
old=max(a,b,c)
print(old)
young=min(a,b,c)
print(young)

